### ISSUE TITLE
Issue with removal of viruses and unclassified taxa

### ISSUE THREAD

**Issue by baptisteavot** [jaeyunsung/GMHI_2020#1]
These lines seems to be resulting in an empty dataframe (since my data does not contain any viruses in the rows):
species_profile_1 <- species_profile[-grep('unclassified', row.names(species_profile)),] 
species_profile_2 <- species_profile_1[-grep('virus', row.names(species_profile_1)),]
I think it's because of a misuse of grep ... I skipped those two lines and it works fine

**Comment by jaeyunsung** [comment]
Lines 33-35 have been updated to accommodate for the rare case wherein no unclassified or virus species are detected using MetaPhlAn2
