### ISSUE TITLE
How to produce species list?

### ISSUE THREAD

**Issue by Mushahid2521** [jaeyunsung/GMHI_2020#3]
Which script can be used to produce the MH_species.txt and MN_species.txt list? 
Thanks a lot.

**Comment by jaeyunsung** [comment]
The R script 'Fig2_TableS1_Table2.R' (https://github.com/jaeyunsung/GMHI_2020/blob/master/Fig2_TableS1_Table2.R) can be used to produce the 'MH_species.txt' and 'MN_species.txt' lists. Please see variables 'H_species' and 'NH_species' in lines # 144 and 145 of the script. I hope this helps, and thanks for your interest!

**Comment by Mushahid2521** [comment]
Thanks it worked.
