### ISSUE TITLE
Understanding H_constant and NH_constant 

### ISSUE THREAD

**Issue by Mushahid2521** [jaeyunsung/GMHI_2020#4]
Sorry if I am wrong. If H_constant is the length of H_species and NH_constant is the length of NH_species then shouldn't the N_constant will be 43 at  [line](https://github.com/jaeyunsung/GMHI_2020/blob/87fe9f6eb96b154683c454067456be48a96bbd9c/Fig2_TableS1_Table2.R#L148) as we got 43 NH_species. 
If not then if you please explain how to calculate the NH_constant.
Thanks

**Comment by jaeyunsung** [comment]
Thank you for getting in touch. 

I think an important part in our methods may have been overlooked. Our answer to your question is carefully described in our scripts and manuscript:
- For a detailed written explanation of the calculation of  H_constant and NH_constant, please go through the “Identifying microbial species more frequently observed in healthy than in nonhealthy (and vice versa)” subsection in the Methods section of our paper (https://www.nature.com/articles/s41467-020-18476-8).
- Also, please go through the lines #69–78 to get an idea of what's going on: https://github.com/jaeyunsung/GMHI_2020/blob/87fe9f6eb96b154683c454067456be48a96bbd9c/Fig2_TableS1_Table2.R#L69-L78 

In case anything is still unclear, please feel free to ask a specific question and state which part that is still confusing.

**Comment by Mushahid2521** [comment]
Thanks a lot for taking your time to explain in detail. 
`H_constant <- median(HC1$H_sig_count[1:26])`

I couldn't understand why we are taking the median of 26 counts as H_constant and 17 for NH_constant and what leads to **7** and **31** in validation respectively.  Another question is how to find the cutoffs range to tune the theta_fold and theta_diff. 
Thanks again.

**Comment by jaeyunsung** [comment]
Hi again. The answers to both questions can be found in the manuscript. We've carefully covered the rationale of those in the Methods section. Specifically,
1) regarding your question on the median counts of 26 and 17:  Please look at p. 14 (of 16) in the pdf file; go to the subsection "Identifying h_{i, MH, MN}, that is, ratio of ψ_{MH} to ψ_{MN}, in sample i:"; and read (b) carefully, especially (b)iii.
2) regarding your question on finding the cutoff ranges: Please look at p. 6 and p. 14 of the pdf file of our manuscript, as well as Supplementary Table 1 and Supplementary Fig. 3. Everything is carefully explained and walks you through examples of what we did.

**Comment by Mushahid2521** [comment]
Thanks a lot for your help. Now I see how this is carefully described. I was testing this approach with OTU data integrating from multiple studies. One issue I am facing is that the relative change in the GMHI value differs between Healthy and Non-Healthy groups but most of the values lies in the negative range.

Another situation is if the sample size is <100 then taking 1% median doesn't work. So in that case how many samples I should take median?
