### ISSUE TITLE
PH/PNH issue

### ISSUE THREAD

**Issue by Mushahid2521** [jaeyunsung/GMHI_2020#5]
Does it only consider the case only when a species is seen both in healthy and nonhealthy samples? Because while calculating PH/PNH, if a species is not seen in nonhealthy sample then PNH will be 0 for that species and PH/PNH will be infinite.

**Comment by jaeyunsung** [comment]
Thank you for your question.

There was no species in our dataset (of 4,347 samples) that was present in either healthy or non-healthy groups only. However, even if there were indeed a case where a species was seen in only one of the two groups, our addition of the pseudocount to PH and PNH allows us to avoid dividing by 0, and thereby permits us to go on to calculate the ratio of PH to PNH. Please refer to our scripts or manuscript for further details.
