### ISSUE TITLE
MetaPhlAn3

### ISSUE THREAD

**Issue by xuahe** [jaeyunsung/GMHI_2020#6]
Hi, I'm wondering is GMHI compatible with Metaphlan3?
Thank you!

**Comment by jaeyunsung** [comment]
Hello, and thanks for your interest in our work.

No, Metaphlan3 and GMHI are not currently compatible with each other. In the coming months, we're coming out with a second version, or GMHI2, that is integrated with Metaphlan3. I hope you can check it out then.

**Comment by fconstancias** [comment]
Any update on that side?

**Comment by fconstancias** [comment]
yes ! https://github.com/danielchang2002/GMWI2
